server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meeting
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB


mybatis-plus:
  mapper-locations: classpath:com/xyongfeng/mapper/xml/*.xml
  # 开启控制台输出语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# host表示允许接收请求的客户端IP,"0.0.0.0" 表示该服务端将接受来自任何网络接口的连接。
socketio:
  host: 0.0.0.0	#监听的ip
  port: 9092		#监听端口
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000


jwt:
  # JWT 存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: meeting-xyf-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer

img:
  # 头像图片储存位置
  head: img/head
  # 面部图片存储位置
  face: img/face
  # 会议截屏位置
  screenshot: img/screenshot
  # 用户意见图片
  adviceImg: img/adviceImg


flask:
  headerUrl: http://127.0.0.1:5000/



