spring:
  profiles:
    active: '@environment@'  #注意YAML配置文件需要加单引号，否则会报错
  datasource:
    url: jdbc:mysql://localhost:3306/meeting
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  # JWT 存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: meeting-xyf-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer